export const ErrorCodes = {
    INVALID_TRANSACTION_DATE: 'INVALID_TRANSACTION_DATE',
    INSUFFICIENT_WALLET_BALANCE: 'INSUFFICIENT_WALLET_BALANCE',
    CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
