export const ErrorCodes = {
    INVALID_TRANSACTION_DATE: 'INVALID_TRANSACTION_DATE',
    INSUFFICIENT_WALLET_BALANCE: 'INSUFFICIENT_WALLET_BALANCE',
    CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
    WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
    WALLET_HAS_ALLOCATED_MONEY: 'WALLET_HAS_ALLOCATED_MONEY',
    SESSION_EXPIRATION_MUST_BE_AFTER_CREATION:
        'SESSION_EXPIRATION_MUST_BE_AFTER_CREATION',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_USERNAME: 'INVALID_USERNAME',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
    PASSWORD_CANNOT_BE_EMPTY: 'PASSWORD_CANNOT_BE_EMPTY',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_SESSION: 'INVALID_SESSION',
    GOAL_MUST_BE_IN_PROGRESS: 'GOAL_MUST_BE_IN_PROGRESS',
    INSUFFICIENT_GOAL_BALANCE: 'INSUFFICIENT_GOAL_BALANCE',
    EXPIRED_GOAL_CANNOT_BE_COMPLETED: 'EXPIRED_GOAL_CANNOT_BE_COMPLETED',
    GOAL_TARGET_AMOUNT_MUST_BE_REACHED: 'GOAL_TARGET_AMOUNT_MUST_BE_REACHED',
    ONLY_EXPIRED_GOALS_CAN_BE_REACTIVATED:
        'ONLY_EXPIRED_GOALS_CAN_BE_REACTIVATED',
    COMPLETED_GOAL_CANNOT_BE_EXPIRED: 'COMPLETED_GOAL_CANNOT_BE_EXPIRED',
    GOAL_WITHOUT_DEADLINE_CANNOT_EXPIRE: 'GOAL_WITHOUT_DEADLINE_CANNOT_EXPIRE',
    GOAL_DEADLINE_MUST_BE_REACHED_BEFORE_EXPIRATION:
        'GOAL_DEADLINE_MUST_BE_REACHED_BEFORE_EXPIRATION',
    GOAL_CURRENT_AMOUNT_CANNOT_EXCEED_TARGET:
        'GOAL_CURRENT_AMOUNT_CANNOT_EXCEED_TARGET',
    GOAL_DEADLINE_CANNOT_ALREADY_BE_EXPIRED:
        'GOAL_DEADLINE_CANNOT_ALREADY_BE_EXPIRED',
    GOAL_MOVEMENT_AMOUNT_MUST_BE_GREATER_THAN_ZERO:
        'GOAL_MOVEMENT_AMOUNT_MUST_BE_GREATER_THAN_ZERO',
    GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
    GOAL_MOVEMENT_REFERENCES_NON_EXISTENT_WALLET:
        'GOAL_MOVEMENT_REFERENCES_NON_EXISTENT_WALLET',
    GOAL_ALREADY_EXISTS: 'GOAL_ALREADY_EXISTS',
    GOAL_DEPOSIT_NOT_FOUND: 'GOAL_DEPOSIT_NOT_FOUND',
    GOAL_MOVEMENT_CANNOT_BE_REVERTED: 'GOAL_MOVEMENT_CANNOT_BE_REVERTED',
    GOAL_DEADLINE_MUST_BE_AT_LEAST_ONE_DAY_AFTER_CREATION:
        'GOAL_DEADLINE_MUST_BE_AT_LEAST_ONE_DAY_AFTER_CREATION',
    MONEY_VALUE_CANNOT_BE_NEGATIVE: 'MONEY_VALUE_CANNOT_BE_NEGATIVE',
    MONEY_CANNOT_HAVE_MORE_THAN_TWO_DECIMAL_PLACES:
        'MONEY_CANNOT_HAVE_MORE_THAN_TWO_DECIMAL_PLACES',
    MONEY_VALUE_MUST_BE_FINITE: 'MONEY_VALUE_MUST_BE_FINITE',
    NAME_CANNOT_BE_EMPTY: 'NAME_CANNOT_BE_EMPTY',
    NAME_CANNOT_EXCEED_MAXIMUM_LENGTH: 'NAME_CANNOT_EXCEED_MAXIMUM_LENGTH',
    UNIT_OF_WORK_NOT_INITIALIZED: 'UNIT_OF_WORK_NOT_INITIALIZED',
    INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',
    INVALID_ENTITY_ID: 'INVALID_ENTITY_ID',
    INVALID_ENTITY_PROPS: 'INVALID_ENTITY_PROPS',
    INVALID_ENTITY_CREATED_AT: 'INVALID_ENTITY_CREATED_AT',
    INVALID_ENTITY_UPDATED_AT: 'INVALID_ENTITY_UPDATED_AT',
    ENTITY_CREATED_AT_CANNOT_BE_AFTER_UPDATED_AT:
        'ENTITY_CREATED_AT_CANNOT_BE_AFTER_UPDATED_AT',
    TRANSFER_SAME_WALLET: 'TRANSFER_SAME_WALLET',
    TRANSFER_CANNOT_BE_REVERTED: 'TRANSFER_CANNOT_BE_REVERTED',
    TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
