export const IDENTITY_TOKENS = {
    SESSION_REPOSITORY: Symbol('SESSION_REPOSITORY'),
    USER_REPOSITORY: Symbol('USER_REPOSITORY'),
    PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
    UNIT_OF_WORK: Symbol('UNIT_OF_WORK'),
};
