export const FINANCE_TOKENS = {
    CATEGORY_REPOSITORY: Symbol('CATEGORY_REPOSITORY'),
    WALLET_REPOSITORY: Symbol('WALLET_REPOSITORY'),
    TRANSACTION_REPOSITORY: Symbol('TRANSACTION_REPOSITORY'),
    TRANSACTION_QUERY: Symbol('TRANSACTION_QUERY'),
};
