export const FINANCE_TOKENS = {
    CATEGORY_REPOSITORY: Symbol('CATEGORY_REPOSITORY'),
    TRANSFER_REPOSITORY: Symbol('TRANSFER_REPOSITORY'),
    WALLET_REPOSITORY: Symbol('WALLET_REPOSITORY'),
    ENSURE_CAN_DELETE_WALLET: Symbol('ENSURE_CAN_DELETE_WALLET'),
    CAN_DELETE_CATEGORY: Symbol('CAN_DELETE_CATEGORY'),
    TRANSACTION_REPOSITORY: Symbol('TRANSACTION_REPOSITORY'),
    TRANSACTION_QUERY: Symbol('TRANSACTION_QUERY'),
    UNIT_OF_WORK: Symbol('UNIT_OF_WORK'),
    FACADE: Symbol('FACADE'),
};
